AllCops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 3.4
  Exclude:
    - "bin/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Style/HashSyntax:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 2

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/YAMLFileRead:
  Enabled: false
