#!/usr/bin/env bash

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/env" "$@"

cd "$DIR"

# bootstrap gem dependencies
if [ "${BUNDLE_WITHOUT:-}" == "" ]; then
  echo -e "${BLUE}Installing Gems for ${PURPLE}development${BLUE}...${OFF}"
else
  echo -e "${BLUE}Installing Gems for ${GREEN}production${BLUE}...${OFF}"
fi

bundle install --local
bundle binstubs --all
