#!/usr/bin/env bash

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/env" "$@"

cd "$DIR"

docker build --build-arg "RUBY_VERSION=$RBENV_VERSION" -t "$REPO_NAME:latest" .
