#!/usr/bin/env bash

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/env" "$@"

cd "$DIR"

export RUBOCOP_CACHE_ROOT="$DIR/tmp/rubocop_cache"

# run linter
echo -e "\n🤖 ${BLUE}Running Rubocop: $(date "+%H:%M:%S")${OFF}\n"

bundle exec rubocop -c .rubocop.yml "$@"
