#! /usr/bin/env bash

set -e

source script/env "$@"

export RUBOCOP_CACHE_ROOT="$DIR/tmp/rubocop_cache"

# run linter
echo -e "\n🤖 ${BLUE}Running Rubocop: $(date "+%H:%M:%S")${OFF}\n"

bundle exec rubocop -c .rubocop.yml "$@"
