#!/usr/bin/env bash

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/env" "$@"

cd "$DIR"

# Add your own logic below for running a ruby application
bundle exec ruby lib/cli.rb
