#! /usr/bin/env bash

set -e

source script/env "$@"

echo -e "📦 ${BLUE}Building tarball${OFF}"

# set BUILD_SHA and BUILD_BRANCH if they are not already set
: "${BUILD_SHA:=$(git rev-parse HEAD)}"
: "${BUILD_BRANCH:=$(git rev-parse --abbrev-ref HEAD)}"

# build and tag the docker image
script/docker-build

docker run -e "BUILD_BRANCH=$BUILD_BRANCH" -e "BUILD_SHA=$BUILD_SHA" \
  -v "$TARBALL_DIR:/app/tarballs" \
  -v "$DIR/.git:/app/.git:ro" \
  "$REPO_NAME" script/build-deploy-tarball
