FROM ruby:4.0.2-slim@sha256:12f002ff598856284c9fd35526712d5431c47d60dd91eb3a00f9e01777c762d5 AS base

ARG TARBALL="undefined"

# create a nonroot user
RUN useradd -m nonroot

WORKDIR /app

# copy tarfile
COPY --chown=nonroot:nonroot ${TARBALL} /tmp/app.tar.gz

# extract the tarfile and remove it from the image layer
RUN tar -zxvf /tmp/app.tar.gz -C /app && rm /tmp/app.tar.gz

# change ownership of /app directory to nonroot user
RUN chown -R nonroot:nonroot /app

# switch to the nonroot user
USER nonroot

# set the environment to production
ENV RUBY_ENV=production
