FROM ruby:4.0.6-slim@sha256:58479f164d5947f852da27a4436c89bb986a811f959c40552bc7f6ccaabcc9c9 AS base

ARG TARBALL="undefined"

# create a nonroot user
RUN useradd -m nonroot

WORKDIR /app

# copy tarfile
COPY --chown=nonroot:nonroot ${TARBALL} /tmp/app.tar.gz

# extract the tarfile and remove it from the image layer
RUN tar -zxvf /tmp/app.tar.gz -C /app && rm /tmp/app.tar.gz

# change ownership of /app directory to nonroot user
RUN chown -R nonroot:nonroot /app

# switch to the nonroot user
USER nonroot

# set the environment to production
ENV RUBY_ENV=production
