#! /usr/bin/env bash

set -e

source script/env "$@"

# set BUILD_SHA and BUILD_BRANCH if they are not already set
: "${BUILD_SHA:=$(git rev-parse HEAD)}"
: "${BUILD_BRANCH:=$(git rev-parse --abbrev-ref HEAD)}"

tarball_name="${PLATFORM}-${ARCH}-${VERSION}-${BUILD_SHA}.tar.gz"

docker build --build-arg "RUBY_VERSION=$RBENV_VERSION" --build-arg "TARBALL=tarballs/$tarball_name" -t "$REPO_NAME-tarball-test:latest" .

# Run the container and capture the output
result=$(docker run --rm "$REPO_NAME-tarball-test:latest" bash -c "/app/script/server 2 3")

# Check if the result is exactly 5
if [[ "$result" == "5" ]]; then
    echo -e "\n✅ Test passed: Output is 5 as expected"
    exit 0
else
    echo -e "\n❌ Test failed: Expected output to be 5, but got: $result"
    exit 1
fi
