name: build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: build

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - if: matrix.os == 'ubuntu-latest'
        uses: GrantBirki/fence@f420993f1cc71720286e1beea00a2de3f2bb604d # pin@main

      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@4c56a21280b36d862b5fc31348f463d60bdc55d5 # pin@v1.301.0
        with:
          bundler: none
          bundler-cache: false

      - name: bootstrap
        run: script/bootstrap

      - name: build
        run: script/build
