name: build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: build

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - if: matrix.os == 'ubuntu-latest'
        uses: GrantBirki/fence@ac903ba12fdf9c4562a4786c53e10c8024a1dd1e # pin@main

      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@6aaa311d81eba98ae12eaffbcb63296ace0efcde # pin@v1.307.0
        with:
          bundler: none
          bundler-cache: false

      - name: bootstrap
        run: script/bootstrap

      - name: build
        run: script/build
