# this workflow is mainly a demo of how you can use the script/tarball command to create a tarball of the repo/project
# adapt this to your own needs

name: tarball

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  tarball:
    name: tarball
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # pin@v1.300.0
        with:
          bundler-cache: true

      - name: tarball
        run: script/tarball

      - name: tarball test
        run: spec/acceptance/tarball-test
