# this workflow is mainly a demo of how you can use the script/tarball command to create a tarball of the repo/project
# adapt this to your own needs

name: tarball

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  tarball:
    name: tarball
    runs-on: ubuntu-latest

    steps:
      - uses: GrantBirki/fence@749baf09a2f94371ebfe439997758604a26e2789 # pin@main
        with:
          container_policy: unsafe_preserve
          allowlist: |
            registry-1.docker.io
            auth.docker.io
            production.cloudfront.docker.com
            deb.debian.org

      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6
        with:
          persist-credentials: false

      - name: tarball
        run: script/tarball

      - name: tarball test
        run: spec/acceptance/tarball-test
