# this workflow is mainly a demo of how you can use the script/tarball command to create a tarball of the repo/project
# adapt this to your own needs

name: tarball

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

cache-mode: none

jobs:
  tarball:
    name: tarball
    runs-on: ubuntu-latest

    steps:
      - uses: openai/fence@530cce8d45da60a7c353da45511639ad5e154e9a # pin@v0.10.1
        with:
          container_policy: unsafe_preserve
          allowlist: |
            registry-1.docker.io
            auth.docker.io
            production.cloudfront.docker.com

      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin@v6
        with:
          persist-credentials: false

      - name: tarball
        run: script/tarball

      - name: tarball test
        run: spec/acceptance/tarball-test
