name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: GrantBirki/fence@ea6de9d504c70a7b3fbe025dcc9fb2718a28f3da

      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@4c56a21280b36d862b5fc31348f463d60bdc55d5 # pin@v1.301.0
        with:
          bundler: none
          bundler-cache: false

      - name: bootstrap
        run: script/bootstrap

      - name: test
        run: script/test
